version: "3.3"

   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./envs/local/django
      - ./envs/local/postgres
    ports:
      - "8000:8000"
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - tor

  tor:
    build:
      context: .
      dockerfile: compose/tor/Dockerfile
    command: /usr/bin/tor
    ports:
      - "9050:9050"
      - "9051:9051"