# Generated by Django 3.1.5 on 2021-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField()),
                ('titre', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('description', models.TextField()),
                ('code_postal', models.CharField(max_length=5)),
            ],
        ),
    ]
