# Generated by Django 3.1.5 on 2021-01-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annonce',
            unique_together={('lien',)},
        ),
    ]
