# Generated by Django 3.1.5 on 2021-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_auto_20210124_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('ATTENTE', 'ATTENTE'), ('VALIDE', 'VALIDE'), ('ERREUR', 'ERREUR')], default='ATTENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='surface',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
