# Generated by Django 3.1.5 on 2021-01-24 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_auto_20210124_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
