# Generated by Django 3.1.5 on 2021-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_auto_20210124_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date_publication',
            field=models.DateField(null=True),
        ),
    ]
