# Generated by Django 3.1.7 on 2021-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_annonce_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='source',
            field=models.CharField(choices=[('LEBONCOIN', 'Leboncoin'), ('PAP', 'Particuliers à particuliers')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('ERREUR', 'En erreur')], default='ATTENTE', max_length=10),
        ),
    ]
